# Generated by Django 5.2.8 on 2025-12-02 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField(default='0700000000')),
                ('tables_reserved', models.IntegerField(default='0')),
                ('guest_count', models.IntegerField(default='0')),
                ('reservation_date', models.DateField(default=datetime.date.today)),
                ('reservation_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
