# Generated by Django 5.2.8 on 2025-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
