# Generated by Django 5.2.8 on 2025-12-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_django_app', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additional_comments',
            field=models.CharField(default='Allergic to gluten', max_length=1000),
        ),
    ]
